### ISSUE TITLE
Trained 'find-and -avoid-v2' Model Results in No Robot Movement During Testing Phase

### ISSUE THREAD

**Issue by wayne-weiwei** [aidudezzz/deepworlds#107]
Hello,

Thank you for this wonderful library! I’ve encountered an issue, and I was hoping you could help me understand what might be going wrong. After training the model, the robot does not move during testing. However, it performs normally during the training phase.

Expected Behavior
The robot should move according to the actions predicted by the model during the test phase.

Actual Behavior
The robot remains stationary during testing and does not perform any actions.

**Comment by tsampazk** [comment]
Hey @wayne-weiwei, thank you for the appreciation! Sorry for the late reply.

Does this issue occur when you run the simulation out-of-the-box or have you made any modifications to it?

**Comment by wayne-weiwei** [comment]
Hi, Thanks for your time. 
I just changed command 'only_test = True', and The robot keeps going backwards. Why is that? It's like he's not learning anything.

**Comment by tsampazk** [comment]
If everything else is cloned from the repository and you only changed `only_test = True` it should be loading the trained agent just for testing.

Your first few lines in the manager should look like this:

https://github.com/aidudezzz/deepworlds/blob/dev/examples/find_and_avoid_v2/controllers/robot_supervisor_manager/robot_supervisor_manager.py#L7-L9

Your directory should have the `experiments/trained_agent` as in the screenshot:

![image](https://github.com/user-attachments/assets/a1e40aee-6365-4c5f-a6e7-aed2c8dfabc6)

I am noting this just to make sure that the [trained_agent_diff_5_agent.zip](https://github.com/aidudezzz/deepworlds/blob/dev/examples/find_and_avoid_v2/controllers/robot_supervisor_manager/experiments/trained_agent/trained_agent_diff_5_agent.zip) is being loaded properly and not some other untrained agent you might have locally.

Let me know if this helps!

**Comment by wayne-weiwei** [comment]
Thank you so much for your help. It works now and it is impressive.
