### ISSUE TITLE
error: DDPG_runner.run()

### ISSUE THREAD

**Issue by wakeupppp** [aidudezzz/deepworlds#13]
Hello! My  `DDPG_runner.run()` has an error, like :`Can't instantiate abstract class CartPoleSupervisor with abstract methods get_default_observation`, and `PPO` has same error.  I don't know if it is caused by my `python3+torch1.6.0`, do you have the similar problem?
![image](https://user-images.githubusercontent.com/39750646/92550326-d240e400-f28d-11ea-81cc-75df4972e848.png)

**Comment by tsampazk** [comment]
Hello, thank you for reporting this issue! It is related to the new release (0.1.1). A fix is on the way.

**Comment by tsampazk** [comment]
@wakeupppp 
Fix is up in the new version of deepbots (0.1.2)! 

Moreover version 2020b of Webots seemed to cause a problem in the cartpole example with the [getVelocity method](https://cyberbotics.com/doc/reference/supervisor?tab-language=python#wb_supervisor_node_get_velocity). It seems to be resolved in version 2020b rev1.

**Comment by wakeupppp** [comment]
It works, thanks!

**Comment by tsampazk** [comment]
@all-contributors please add @wakeupppp  for bug
