### ISSUE TITLE
[CartPole] Fix convergeness issues

### ISSUE THREAD

**Issue by KelvinYang0320** [aidudezzz/deepworlds#62]
The agents can't reach the solved condition in few episodes.
- [x] Robot-supervisor: Discrete CartPole
  * https://drive.google.com/drive/folders/1n6HeZWg9zxwABPxg3u0nSldvw5DfFD84?usp=sharing
- [x] Robot-supervisor: Discrete CartPole (SB3)
  * https://drive.google.com/drive/folders/1s-ua1fPanaMTzEED48otAdBpfBGh3Keg?usp=sharing
- [x] Robot-supervisor: Continusous CartPole
  * https://drive.google.com/drive/folders/1AQme2Z-kH4XHhH6aBudi-WkazSkodfjb?usp=sharing
- [x] Emitter-receiver: Discrete CartPole
  * Task is not solved in 2000 episodes, but the agent works well in test mode and the score is always 197.
  * https://drive.google.com/drive/folders/1P7VPB4ac-_5asCbWCSDtIencIDll8cwH?usp=sharing
- [x] Emitter-receiver: Continusous CartPole
  * Task is not solved in 10000 episodes, but the agent works well in test mode and the score is always 197.
  * https://drive.google.com/drive/folders/1P7VPB4ac-_5asCbWCSDtIencIDll8cwH?usp=sharing

**Comment by KelvinYang0320** [comment]
**Discrete CartPole Emitter-Receiver**
I change `episodeLimit` from 200 to 10000, but it still didn't reach a score of 195.0.

https://user-images.githubusercontent.com/49781698/172836196-1a16127f-4dc8-4d13-bcd4-19a96f09386d.mp4

|Episode scores over episodes|Average episode action probability over episodes|
|---|---|
|![Figure_1](https://user-images.githubusercontent.com/49781698/172836914-763fc5de-084a-452a-b155-52048917195f.png)|![Figure_2](https://user-images.githubusercontent.com/49781698/172836924-348884c0-bc4a-4815-bdb5-e112f798282d.png)|

**Comment by tsampazk** [comment]
@KelvinYang0320 is this issue really resolved by issue #68 ? Asking because github automatically closes linked issues. If not, or if we are not sure we can reopen it.

**Comment by KelvinYang0320** [comment]
@tsampazk Thanks for the reminder.
Our agents work well with Robot-Supervisor scheme.
I will check if the issue is resolved in Emitter - receiver scheme as well.
If there are still some problems, I will reopen it.

**Comment by KelvinYang0320** [comment]
@tsampazk I think we can close this issue.
I have edited the first comment for the results.

**Comment by tsampazk** [comment]
Good job @KelvinYang0320, thank you very much for the detailed documentation.

**Comment by KelvinYang0320** [comment]
Uploaded Robot-supervisor: Discrete CartPole (SB3) to Google Drive.
